---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: master
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: master
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      branch: master
    augeasproviders_ssh:
      repo: https://github.com/simp/augeasproviders_ssh
      branch: master
    autofs: https://github.com/simp/pupmod-simp-autofs
    concat: https://github.com/simp/puppetlabs-concat
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    nfs: https://github.com/simp/pupmod-simp-nfs
    nsswitch: https://github.com/simp/puppet-nsswitch
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    postfix: https://github.com/simp/pupmod-simp-postfix
    simp: https://github.com/simp/pupmod-simp-simp
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    # Used by Postfix
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    simplib: https://github.com/simp/pupmod-simp-simplib
    sssd: https://github.com/simp/pupmod-simp-sssd
    ssh: https://github.com/simp/pupmod-simp-ssh
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    sudo: https://github.com/simp/pupmod-simp-sudo
    sudosh: https://github.com/simp/pupmod-simp-sudosh
    svckill: https://github.com/simp/pupmod-simp-svckill
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    simp_nfs: "#{source_dir}"
