---
fixtures:
  repositories:
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_sysctl: https://github.com/simp/augeasproviders_sysctl
    autofs: https://github.com/simp/pupmod-simp-autofs
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat: https://github.com/simp/puppetlabs-concat
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    nfs: https://github.com/simp/pupmod-simp-nfs
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    svckill: https://github.com/simp/pupmod-simp-svckill

    # Required for the acceptance test
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    haveged: https://github.com/simp/pupmod-simp-haveged
    iptables: https://github.com/simp/pupmod-simp-iptables
    mount_core:
      repo: https://github.com/simp/pupmod-puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
    nsswitch: https://github.com/simp/puppet-nsswitch
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    simp: https://github.com/simp/pupmod-simp-simp
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    sssd: https://github.com/simp/pupmod-simp-sssd
    ssh: https://github.com/simp/pupmod-simp-ssh
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    sudo: https://github.com/simp/pupmod-simp-sudo
    systemd: https://github.com/simp/puppet-systemd
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
