---
HOSTS:
  server7:
    roles:
    - default
    - ldap
    - nfs_server
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  client7:
    roles:
    - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  server8:
    roles:
    - nfs_server
    - 389ds
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
  client8:
    roles:
    - client
    - agent
    - el8
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
        - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
  ssh:
    keepalive: true
    keepalive_interval: 10
    keepalive_maxcount: 60
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
