<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:

  server7:
    roles:
      - server
      - default
      - master
      - ldap
      - nfs_server
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  client7:
    roles:
      - client
      - agent
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  server8:
    roles:
      - server
      - nfs_server
      - el8
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  client8:
    roles:
      - client
      - agent
      - el8
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      simp:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/8/x86_64/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
  synced_folder: disabled
  # vb_gui: true
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
